# Generated by Django 4.2.1 on 2023-06-13 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('main_image', models.ImageField(null=True, upload_to='store/images/%Y/%m/%d')),
                ('image1', models.ImageField(null=True, upload_to='store/images/%Y/%m/%d')),
                ('image2', models.ImageField(null=True, upload_to='store/images/%Y/%m/%d')),
                ('image3', models.ImageField(null=True, upload_to='store/images/%Y/%m/%d')),
                ('date_creation', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-date_creation'],
            },
        ),
    ]
