# Generated by Django 4.2.1 on 2023-06-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
