# Generated by Django 4.2.1 on 2023-06-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
